name: Build Core

on:
  pull_request:
    branches:
      - main
    paths:
      - "core/**"

jobs:
  build-gradle-project:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle ?8.7
        id: setup-gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run build with Gradle Wrapper
        run: gradle build

      - run: echo "The gradle version was ${{ steps.setup-gradle.outputs.gradle-version }}"
